name: CICD

on:
  push:
    branches: [ "master" ]



jobs:
  telnet-send:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python-version }}
    - name: Telnet Send
      run: python ddos/ddos.py